<b> Arrays in python <b>

In [1]:
import array
my_array=array.array('i',[1,2,3,4,5])

In [2]:
my_array

array('i', [1, 2, 3, 4, 5])

In [3]:
type(my_array)

array.array

In [4]:
my_float_arr = array.array('f',[1.2,3.600])

In [5]:
type(my_float_arr)

array.array

<b> NumPy in Python <b>

In [6]:
import numpy as np


In [7]:
arr = np.array([1,2,3,4,5])

In [8]:
arr

array([1, 2, 3, 4, 5])

In [9]:
type(arr)

numpy.ndarray

In [10]:
# 0D array

zero_arr = np.array(50)

In [11]:
zero_arr

array(50)

In [12]:
#1D array

oned_arr = np.array([1,2,34])

In [13]:
oned_arr

array([ 1,  2, 34])

In [14]:
type(oned_arr)

numpy.ndarray

In [16]:
#2d array

twod_Arr = np.array([[1,2,3],[4,5,6]])
                     

In [17]:
twod_Arr

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
int_list = [1,2,3,4,5]
my_int_arr = np.array(int_list)
my_int_arr

array([1, 2, 3, 4, 5])

In [21]:
mixed_ele_list = [1,1.1,2,4.5,6.8,"hello"]
my_mixed_array = np.array(mixed_ele_list)

In [22]:
my_mixed_array

array(['1', '1.1', '2', '4.5', '6.8', 'hello'], dtype='<U32')

In [23]:
my_int_arr

array([1, 2, 3, 4, 5])

In [24]:
to_back_list = my_int_arr.tolist()

In [25]:
type(to_back_list)

list

In [26]:
print(my_int_arr)

[1 2 3 4 5]


In [28]:
my_int_arr

array([1, 2, 3, 4, 5])

<b> Properties of NumPy arrays <b>

In [27]:
my_int_arr

array([1, 2, 3, 4, 5])

In [29]:
type(my_int_arr)

numpy.ndarray

In [30]:
my_int_arr.dtype

dtype('int32')

In [31]:
my_int_arr.ndim

1

In [32]:
my_int_arr.size

5

In [33]:
my_int_arr.shape

(5,)

<b> Prepopulates arrays <b> 

In [34]:
zeros = np.zeros(6)

In [35]:
zeros

array([0., 0., 0., 0., 0., 0.])

In [36]:
zeros_int = np.zeros(6, dtype=int)

In [37]:
zeros_int

array([0, 0, 0, 0, 0, 0])

In [38]:
ones_arr = np.ones(3)

In [39]:
ones_arr

array([1., 1., 1.])

In [40]:
np.empty(10)

array([1.00911748e-311, 1.67982320e-322, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 1.16095484e-028, 1.47278631e+179, 9.08367237e+223,
       1.16466228e-028, 1.58377683e-319])

In [41]:
arrange_array = np.arange(1,10)

In [42]:
arrange_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a1 = np.arange(5,50,3)
a1

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [45]:
#2D arrays 

l1 = [1,2,3]
l2 = [4,5,6]
l3 = [7,8,9]

two_d_array = np.array([l1,l2,l3])
two_d_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
type(two_d_array)

numpy.ndarray

In [47]:
two_d_array.dtype

dtype('int32')

In [48]:
two_d_array.ndim

2

In [49]:
two_d_array.size

9

In [50]:
two_d_array.shape

(3, 3)

<b> NumPy COmputations <b> 

In [51]:
l1 = [1,2,3,4,5]
a1 = np.array(l1)
a1

array([1, 2, 3, 4, 5])

In [52]:
l2 = [[1,2,3],[4,5,6]]
a2 = np.array(l2)
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
a1

array([1, 2, 3, 4, 5])

In [54]:
a1[0]

1

In [55]:
a1[1]

2

In [56]:
a1[-1]

5

In [57]:
a1

array([1, 2, 3, 4, 5])

In [58]:
a1[2]

3

In [59]:
a1[2] = 3333

In [60]:
a1

array([   1,    2, 3333,    4,    5])

In [61]:
a1[:2]

array([1, 2])

In [62]:
a1[2:]

array([3333,    4,    5])

In [63]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
a2[0,0]

1

In [65]:
a2[0,1]

2

In [66]:

a2[: :]

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
a1

array([   1,    2, 3333,    4,    5])

In [68]:
a_subarr = a1[:3]
a_subarr

array([   1,    2, 3333])

In [69]:
type(a_subarr)

numpy.ndarray

In [70]:
a_subarr[0]

1

In [71]:
a_subarr[0] = 100

In [72]:
a_subarr

array([ 100,    2, 3333])

In [73]:
a1

array([ 100,    2, 3333,    4,    5])

In [74]:
a_copyarr = a1.copy()

In [75]:
a_copyarr

array([ 100,    2, 3333,    4,    5])

In [76]:
a_copyarr[0] = 50

In [77]:
a_copyarr

array([  50,    2, 3333,    4,    5])

In [78]:
a1

array([ 100,    2, 3333,    4,    5])

<b> Reshaping <b>

In [79]:
one_Arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [80]:
one_Arr.ndim

1

In [81]:
two_d_Arr = one_Arr.reshape(4,3)

In [82]:
two_d_Arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [83]:
two_d_Array = one_Arr.reshape(3,4)
two_d_Array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [84]:
two_d_Array_ex = one_Arr.reshape(5,5)

ValueError: cannot reshape array of size 12 into shape (5,5)

In [85]:
oned_Arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])

In [91]:
two_d_Arr = oned_Arr.reshape(2,2)

ValueError: cannot reshape array of size 13 into shape (2,2)

In [89]:
two_d_Arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [92]:
one_Arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [96]:
two_arr = one_Arr.reshape(6,2)

In [97]:
two_arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [98]:
one_Arr_thirtheen = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])

In [102]:
reshaping = one_Arr_thirtheen.reshape(13,1)

In [103]:
reshaping

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13]])

In [104]:
reshaping.ndim

2

In [105]:
a1

array([ 100,    2, 3333,    4,    5])

In [106]:
sum(a1)

3444

In [107]:
np.sum(a1)

3444

#exercise : 

- Create an np array with 100000 elements 
- use the sum() vs np.sum() on the created array . ALso use %timeit

In [108]:
%timeit np.sum(a1)

4.52 µs ± 233 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [109]:
a1

array([ 100,    2, 3333,    4,    5])

In [110]:
a1+5

array([ 105,    7, 3338,    9,   10])

In [111]:
a1 ** 2

array([   10000,        4, 11108889,       16,       25], dtype=int32)

In [112]:
np.add(a1,5)

array([ 105,    7, 3338,    9,   10])

In [113]:
a1

array([ 100,    2, 3333,    4,    5])

In [114]:
a1

array([ 100,    2, 3333,    4,    5])

In [115]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
a2 + 3

array([[4, 5, 6],
       [7, 8, 9]])

In [117]:
np.sum(a2)

21

In [118]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
np.sum(a2,axis=0)

array([5, 7, 9])

In [120]:
np.sum(a2,axis=1)

array([ 6, 15])

In [121]:
a1

array([ 100,    2, 3333,    4,    5])

In [122]:
a1 == 5 # Linear search ?

array([False, False, False, False,  True])

In [123]:
a1 !=5 

array([ True,  True,  True,  True, False])

In [124]:
a2 == 5

array([[False, False, False],
       [False,  True, False]])

In [125]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
a1

array([ 100,    2, 3333,    4,    5])

In [128]:
np.all(a1 < 5000)

True

In [129]:
np.any(a1 > 500)

True

In [130]:
np.any(a1 > 5000)

False

In [131]:
a1

array([ 100,    2, 3333,    4,    5])

In [132]:
a1.max()

3333

In [133]:
a1.min()

2

In [134]:
a1.mean()

688.8

In [135]:
a1.std()

1322.626689584026

In [136]:
a1.var()

1749341.3599999999

In [137]:
a1.sort()

In [138]:
a1

array([   2,    4,    5,  100, 3333])

In [142]:
np.any((a1>5) & (a1<10))

False

In [143]:
np.sum((a1>5) | (a1<10))

5

In [144]:
a1

array([   2,    4,    5,  100, 3333])

In [145]:
a1 > 10

array([False, False, False,  True,  True])

<b> Linear Algebra using NumPy <b>

In [ ]:
#Fruit seller sold 20 mangoes and 10 oranges on Friday for a total of 
#Rs. 350. He sold 17 mangoes and 22 oranges for Rs. 500 on saturday.
#Price of fruits dint change both days. What's the price of 1 mango and 1 orange ?

In [146]:

# 20x + 10y = 350
# 17x + 22y = 500

A = np.array([[20,10],[17,22]])

B = np.array([350,500])

In [147]:
X = np.linalg.solve(A,B)
print(X)

[10. 15.]


In [149]:
X = np.eye(2)
print(X)

[[1. 0.]
 [0. 1.]]


In [ ]:
# Explore !! 