### **Numpy Tutorials**

# Installing third party modules
# See the instructions at:
# https://docs.python.org/3/installing/index.html


In [1]:
import numpy as np


In [2]:
print(dir(np)) # list of methods for a list of numpy

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__'

### List
Lists are used to store multiple items in a single variable.


In [45]:
a = [1,2,3,4] # simple ordered collection

print(a[0]) # first element
print(a[-1]) # last element
print(a[:2]) # first two elements
print(a[0:3]) # first three elements
print(a[1:3])  # second to third elements
print(a[:])  # to print all elements
print(type(a)) # Type 
print(len(a)) # length 


1
4
[1, 2]
[1, 2, 3]
[2, 3]
[1, 2, 3, 4]
<class 'list'>
4


In [4]:
a.append(7) # adds an element to the end
print (a)

a.extend([9,11,13]) # concatenates a list at the end
print (a)
a.pop() # Removes one element at the end.
print (a)


[1, 2, 3, 4, 7]
[1, 2, 3, 4, 7, 9, 11, 13]
[1, 2, 3, 4, 7, 9, 11]


In [5]:
#List Comprehension

cities=['indore','kolkata','mumbai','pune','guahati','abc']
newlist=[]
for i in cities:
    if 'a' in i:
        newlist.append(i)
        
print(newlist)

['kolkata', 'mumbai', 'guahati', 'abc']


### Dictionary

Dictionaries are used to store data values in key:value pairs

In [6]:
obs = {'Radio':'VLA,GMRT', 'Xray':'Chandra', 'Optical':'Hubble', 'Gamma':'Fermi', 'IR':'Herschel'}
print(type(obs))
print(obs.keys(), obs.values())
obs['Radio']

<class 'dict'>
dict_keys(['Radio', 'Xray', 'Optical', 'Gamma', 'IR']) dict_values(['VLA,GMRT', 'Chandra', 'Hubble', 'Fermi', 'Herschel'])


'VLA,GMRT'

In [7]:
obs.update({'Submm':['SMA', 'PdBI', 'ALMA']})         # Dictionary can be updated with new key value pair.
obs['Xray'] = ['Chandra', 'XMM Newton']               # This is a mutable object just like the list
print(obs)

{'Radio': 'VLA,GMRT', 'Xray': ['Chandra', 'XMM Newton'], 'Optical': 'Hubble', 'Gamma': 'Fermi', 'IR': 'Herschel', 'Submm': ['SMA', 'PdBI', 'ALMA']}


In [8]:
#Creating an n- dimensional array
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
type(a) # Type 
a.shape # Shape of the array


(4,)

In [10]:
#Adding Array with numpy
a=[1,2,3,4]
b=[5,6,7,8]
a_1=np.array(a)
b_1=np.array(b)
print(a+b)
print(a_1 +b_1)

[1, 2, 3, 4, 5, 6, 7, 8]
[ 6  8 10 12]


In [11]:
#Implicit and explicit datatype declaration
ai=np.array([1,2,3])
ac=np.array([1j,2,3.])
af=np.array([1,2,3.])

print(ai.dtype) # datatype of the array
print(af.dtype)
print(ac.dtype)

int64
float64
complex128


In [12]:
# Another example of implicit and explicit datatype declaration

ac=np.array([1,2,3],complex)
af=np.array([1,2,3],float)
afn = np.array([1.11234557585645893656,2.452568425968569654], np.double ) # numpy double type
print(ac)
print(af)
print(afn)


[1.+0.j 2.+0.j 3.+0.j]
[1. 2. 3.]
[1.11234558 2.45256843]


In [13]:
#Define your own data type
dt=np.dtype([('value',int),('status',bool)])
a=np.array([(0,True),(100,False)],dtype=dt)
print(a['value'])
print(a['status'])



[  0 100]
[ True False]


In [14]:
#Convenience functions to create arrays
zero=np.zeros(3)
print(zero)
one=np.ones(3)
print(one)
o=np.ones((3,10)) # Make 3x10 matrix
print(o)

[0. 0. 0.]
[1. 1. 1.]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [15]:
#How to create multidimensional array
l=[[1,2,3],[4,5,9]]
a=np.array(l)
print(l)
print(a)
print(l[1][2])
print(a[1][2])
print(a[0,1])

[[1, 2, 3], [4, 5, 9]]
[[1 2 3]
 [4 5 9]]
9
9
2


In [16]:
#Array attributes

print(a.shape) # the dimensions
print(a.ndim) # number of dimensions
print(a.size) #total number of elements
print(a.dtype) # type of the data

(2, 3)
2
6
int64


In [17]:
b=np.linspace(0,10,11) # Step size is float
print(b)
c=np.arange(0,10,1) # step size is interger
print(c)
m=np.logspace(0,10,11) 
print(m)



[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[0 1 2 3 4 5 6 7 8 9]
[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09
 1.e+10]


In [18]:
b.shape


(11,)

In [19]:
#Write array to a file as text or binary
f=open('filename.txt','w+') # open file 
b.tofile(f)
f.close()

In [20]:
#Construct an array from data in a text or binary file
x=np.fromfile('filename.txt',dtype=float)
print(x)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


#MATHEMATICAL OPERATION

In [21]:
a=np.linspace(0,10,11) # start, end (included), number of points
b=np.linspace(0,20,11)

In [22]:
print(f"a={a} \n b ={b}")

a=[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] 
 b =[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [23]:
print(f"sum(a) = {np.sum(a)}")  # Sum of a 
print(f"mean(a) = {np.mean(a)}") # Mean of the a

print(f"2*a = {2*a}") # multiplication by 2
print(f"a/2 = {a/2}") # division by 2
print(f"a+b = {a+b}") # Add a+b

sum(a) = 55.0
mean(a) = 5.0
2*a = [ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]
a/2 = [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
a+b = [ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27. 30.]


In [24]:
# Simple power, multiplication etc are done elementwise.

print(f"a*b = {a*b}")
print(a)
print(f"a^2 = {a**2}")

a*b = [  0.   2.   8.  18.  32.  50.  72.  98. 128. 162. 200.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
a^2 = [  0.   1.   4.   9.  16.  25.  36.  49.  64.  81. 100.]


#Matrix Opetration

In [25]:
a = np.ones((3,3)) # create matrix using an array
b = np.diag([1,3,5])



In [26]:
aa=np.matrix(np.arange(9).reshape(3,3)) # 3x3 matrix using matrix 
bb=np.matrix(np.linspace(0,9,9).reshape(3,3))

In [27]:
print("a=\n",a,"\nb=\n",b)

print("\n\n Matrix Multiplication \n\n")
print("Elementwise Multiplication > \n",a*b)
print("Dot Product > \n",a.dot(b))
print("Cross Product > \n",np.cross(a,b))

a=
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 
b=
 [[1 0 0]
 [0 3 0]
 [0 0 5]]


 Matrix Multiplication 


Elementwise Multiplication > 
 [[1. 0. 0.]
 [0. 3. 0.]
 [0. 0. 5.]]
Dot Product > 
 [[1. 3. 5.]
 [1. 3. 5.]
 [1. 3. 5.]]
Cross Product > 
 [[ 0.  1. -1.]
 [-3.  0.  3.]
 [ 5. -5.  0.]]


In [28]:
# Same example using matrix
print("aa=\n",aa,"\nb=\n",bb)

print("\n\n Matrix Multiplication \n\n")
print("Elementwise Multiplication > \n",aa*bb)
print("Dot Product > \n",aa.dot(bb))
print("Cross Product > \n",np.cross(aa,bb))

aa=
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 
b=
 [[0.    1.125 2.25 ]
 [3.375 4.5   5.625]
 [6.75  7.875 9.   ]]


 Matrix Multiplication 


Elementwise Multiplication > 
 [[ 16.875  20.25   23.625]
 [ 47.25   60.75   74.25 ]
 [ 77.625 101.25  124.875]]
Dot Product > 
 [[ 16.875  20.25   23.625]
 [ 47.25   60.75   74.25 ]
 [ 77.625 101.25  124.875]]
Cross Product > 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [29]:
# Matrix Determinant & Inverse matrix calculation

N = np.array([[3,0,2],[2,0,-2],[0,1,1]])

det=np.linalg.det(N)
print("\nDeterminant:", np.round(det))
print("Inverse Matrix \n",np.linalg.inv(N))



Determinant: 10.0
Inverse Matrix 
 [[ 0.2  0.2  0. ]
 [-0.2  0.3  1. ]
 [ 0.2 -0.3 -0. ]]


In [30]:
# Transpose of the matrix 

trans_x=np.transpose(x)
trans_x_short=x.T  # short form 
print("Transpose of matrix \n")
print(trans_x)

Transpose of matrix 

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [31]:
# Eigen value & vector calculation
y = np.array([[0,1],[-2,-3]])

eigvals, eigvecs = np.linalg.eig(y)

print("Eigen Values > ",eigvals)
print("Eigen Vectors > \n",eigvecs)

Eigen Values >  [-1. -2.]
Eigen Vectors > 
 [[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


In [32]:
# Estimate a covariance matrix
x = np.array([[0, 2, 5], [1, 1, 7], [2, 0 , 3]]) 
cov=np.cov(x.T)

In [33]:
C_01=cov[0,1] # Covariance of zero one element
print(C_01)

-1.0


**Trace**

The trace is the sum of diagonal elements in a square matrix.

In [34]:
# Trace of the matrix
trace_x=np.trace(x)
print(f"Trace :  {trace_x}")

Trace :  4


**Rank**

The maximum number of linearly independent column vectors or row vectors

In [35]:
# Rank 
rank = np.linalg.matrix_rank(x)
print("\nRank:", rank)


Rank: 3


In [36]:
#
N = np.array([[3,0,2],[2,0,-2],[0,1,1]],dtype=int)
eigenvals, eigenvecs=np.linalg.eig(N)
trace=np.round(sum(eigenvals))

print(f"Trace = {trace}")


Trace = (4+0j)


### Trigonometric functions

In [37]:
# Sine function
x=np.linspace(0,360,361)
#print(x)
rad_x=np.deg2rad(x)  # degree to radian convert
#print(rad_x)
sin=np.sin(rad_x) # Make sine functions
#print(y)
Sine_square= sin**2
cos=np.cos(rad_x)
tan=np.tan(rad_x)

In [38]:
Sine_square= y**2

In [39]:
#Inverse of the trigonometric functions
inv_sin=np.arcsin(sin) # Sine Inverse
inv_cos=np.arccos(cos)  # Cosine Inverse
inv_tan=np.arctan(tan) # Tangent inverse
#print(inv_tan)

In [40]:
# Hyperbolic functions
sineh=np.sinh(rad_x) #Hyperbolic sine
cosh=np.cosh(rad_x) #Hyperbolic cos
tah=np.tanh(rad_x) #Hyperbolic tan

In [41]:
# Some mathematical functions
exp=np.exp(2) # exponential func
log=np.log(2) #Natural logarithm
log10=np.log10(1000) #the base 10 logarithm of the input array


### Miscellaneous


In [42]:
x=np.linspace(0,10,11)
square=x**2 # Square of an array
sqrt=np.sqrt(x) # Squre root of an array
cbrt=np.cbrt(x) # Cube root of an array
fabs=np.fabs(x) # absolute values 




### Random number generation

Numpy has a special attribute for generating random numbers using the Mersenne Twister Pseudo Random Number Genrator.


In [43]:
a = np.random.rand(4)                 # 1D array with 4 uniform random numbers between [0, 1]
print(a)

l1 = 3
l2 = 6
a = l1 + (l2 - l1)*np.random.rand(10) # 1D array with 10 uniform random numbers between [3.0, 6.0]
print(a)

[0.5902146  0.48758697 0.87300733 0.05674647]
[4.9137438  4.5191671  4.19062282 3.01041631 3.44863102 5.952848
 3.69754723 3.4316769  4.67572411 4.35684753]


### Questions for practice:



Q1.  Create an array of length 10, using Fibonacci series. (First create Fibonacci series using Pyhton). 

Q2. Find the eigen values, trace, eigen vectors, determinent and inverse of the following matrix:

$$ A=
\left[\begin{array}{ccc}\dfrac{5}{6} & \dfrac{1}{6} & 0\\
         	\dfrac{5}{6} & 0           & \dfrac{1}{6} \\
         	0           & \dfrac{5}{6} & \dfrac{1}{6}
        	\end{array}
\right] $$

Q3.   Create an array of length 10 using random number generator, then print even and odd elements in new arrays.

  



